### ISSUE TITLE
Latest update breaks import

### ISSUE THREAD

**Issue by mockdeep** [hufan-akari/seamless-scroll-polyfill#147]
When we upgrade from 2.3.0 → 2.3.3 we are no longer able to use `seamless-scroll-polyfill`. We've got the same lines as [in the readme](https://github.com/magic-akari/seamless-scroll-polyfill#use-polyfill-to-patch-all-methods), but it breaks in both Chrome and Firefox on the `polyfill()` line. The output isn't very clear, but the error that comes back is `Uncaught TypeError: Object(...) is not a function`. We're using Webpack for compilation. It looks like `polyfill` is getting imported as `undefined`.

```
Uncaught TypeError: Object(...) is not a function
    at ./app/javascript/packs/application.ts (application.ts:3:1)
    at __webpack_require__ (bootstrap:63:1)
    at 0 (log.js:48:1)
    at __webpack_require__ (bootstrap:63:1)
    at bootstrap:198:1
    at bootstrap:198:1
```

**Comment by magic-akari** [comment]
webpack is more complicated than I thought.
- Related issue: https://github.com/webpack/webpack/issues/4674

I will fix this soon.

**Comment by mockdeep** [comment]
Great, it works, thanks!
